`docker stop --time` increased to 5 seconds
When my company's (Windows) build infrastructure is under heavy load, Jenkins pipelines start failing because Docker containers cannot be stopped in 1 second:

```
java.io.IOException: Failed to kill container '84ed22ea737f82f2e0a51e813cc9b807c6a48f7154ebffc360ca365fd27ed248'.
12:04:11  	at org.jenkinsci.plugins.docker.workflow.client.DockerClient.stop(DockerClient.java:184)
```